version: "3.8"

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/num-converter
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
